version: "3.8"

services:
  client:
    image: forest_client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: forest_client
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - forests
    links:
      - server

  server:
    image: forest_server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: forest_server
    command: uvicorn app:app --host 0.0.0.0 --port 3001
    restart: unless-stopped
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - forests

networks:
  forests:
    driver: bridge
